src/app/dman_helper.cpp
修复1050wayland模式无法搜索时添加了相关配置，可能与sw架构不适配
Log: sw架构帮助手册无法搜索
Bug: https://pms.uniontech.com/bug-view-117079.html
=> fix: sw架构帮助手册无法搜索

src/view/web_window.cpp
fix: Bug-107188 帮助手册长按最大化/还原按钮显示分屏菜单以后会立即消失
=> fix: Bug-107188 帮助手册长按最大化/还原按钮显示分屏菜单以后会立即消失

src/app/dman.cpp, src/dbus/com.deepin.Manual.Open.service
Description: qtwayland中设置的appid为：org.deepin.dman，导致无法找到对应的desktop,所以启动图标 错误，程序中设置desktop为deepin-manual.desktop。更改dbus启动方式，可以直接用dman启动
Log: 在终端输入“dman”启动应用，任务栏图标显示错误
Bug: https://pms.uniontech.com/bug-view-142917.html
=> fix: 在终端输入“dman”启动应用，任务栏图标显示错误

src/controller/search_db.cpp, src/controller/search_db.h, src/controller/search_manager.cpp, src/controller/search_manager.h, src/controller/window_manager.cpp, src/controller/window_manager.h, src/view/web_window.cpp, src/view/web_window.h
Description: 在关闭帮助手册的时候，删除数据库并新建，重新通过dmanHelper加载数据
Log: 数据库中已有数据不能及时同步其他应用的md内容更新
Bug: https://pms.uniontech.com/bug-view-160195.html
=> fix: 数据库中已有数据不能及时同步其他应用的md内容更新

src/base/utils.cpp
XDG_DATA_DIRS可能为空，若默认检索目录为空，则预置/usr/share路径到默认检索路径列表
Log: 修复主界面应用名未翻译为中文的问题
Bug: https://pms.uniontech.com/bug-view-185433.html# 请为您的变更输入提交说明。以 '#' 开始的行将被忽略，而一个空的提交
=> fix: 修复主界面应用名未翻译为中文的问题

src/base/utils.cpp
XDG_DATA_DIRS可能为空，若默认检索目录为空，则预置/usr/share路径到默认检索路径列表
Log: 修复主界面应用名未翻译为中文的问题
Bug: https://pms.uniontech.com/bug-view-185433.html# 请为您的变更输入提交说明。以 '#' 开始的行将被忽略，而一个空的提交
=> fix: 修复主界面应用名未翻译为中文的问题 (#429)

src/CMakeLists.txt, src/app/dman.cpp, src/app/dman_helper.cpp, src/base/utils.cpp, src/base/utils.h
为保证在其他平台正常构建，取消JudgeLinglong接口判断，在下一笔提交中使用patch补丁进行玲珑构建条件编译
Log: 去掉玲珑构建相关配置
=> chore: 去掉玲珑构建相关配置

src/controller/config_manager.cpp, src/controller/config_manager.h, src/controller/window_manager.cpp, src/view/manual_proxy.cpp, src/view/web_window.cpp
程序会卡在QSettings::sync()接口，查阅资料，该接口不必显式调用，QSettings对象被析构时，会自动调用sync
接口，因此去掉所有显式调用sync接口地方，仅析构QSettings对象即可。
Log: 修复pangw架构下，多次重启帮助手册，有概率打开延迟15秒以上的问题
Bug: https://pms.uniontech.com/bug-view-185869.html
=> fix: 修复pangw架构下，多次重启帮助手册，有概率打开延迟15秒以上的问题

src/base/utils.cpp, src/base/utils.h, src/view/manual_proxy.cpp
玲珑环境下资源文件路径有变更，查询desktop文件，需要遍历XDG_DATA_DIRS中的路径
Log: 修复应用图标显示撕裂图的问题
Bug: https://pms.uniontech.com/bug-view-184047.html
=> fix: 修复应用图标显示撕裂图的问题

src/view/web_window.cpp, src/view/web_window.h
看图界面为模态界面，锁屏或息屏时需要显式隐藏看图界面，才能将鼠标事件传递给主线程
Log: 修复帮助手册打开图片，锁屏/解锁后，帮助手册无法操作的问题
Bug: https://pms.uniontech.com/bug-view-189621.html
=> fix: 修复帮助手册打开图片，锁屏/解锁后，帮助手册无法操作的问题

src/CMakeLists.txt, src/app/dman_helper.cpp, src/dbus/dmanwatcher.cpp, src/dbus/dmanwatcher.h, src/view/theme_proxy.cpp, tests/CMakeLists.txt
后端内置定时器，每5秒检查前端dman是否存在，若不存在，则后端dmanHelper退出
Log: 修复系统启动后dmanHelper成为常驻进程的问题
=> fix: 修复系统启动后dmanHelper成为常驻进程的问题

debian/changelog, src/base/utils.cpp, src/resources/CMakeLists.txt, src/resources/org.deepin.manual.metainfo.xml, src/view/manual_proxy.cpp
由于launcher的接口更改,无法获取已安装应用列表
Log:
Issues: https://github.com/linuxdeepin/developer-center/issues/6902
=> fix: missing app list

src/controller/window_manager.cpp, src/view/web_window.cpp
修复双屏扩展模式下，帮助手册在主屏最大化再还原，窗口会直接显示到副屏
Log: 修复双屏扩展模式下，帮助手册在主屏最大化再还原，窗口会直接显示到副屏
Bug: https://pms.uniontech.com/bug-view-244417.html
=> fix: 双屏扩展模式下，帮助手册在主屏最大化再还原，窗口会直接显示到副屏

src/view/manual_proxy.cpp
修复老版本浏览器无法打开视频指南链接问题
Log: 修复老版本浏览器无法打开视频链接问题
Bug: https://pms.uniontech.com/bug-view-249541.html
=> fix: 老版本浏览器无法打开视频链接

src/base/utils.cpp
标题由“帐户设置” 改为 “账户设置”
Log:  修改标题账户设置
Bug: https://pms.uniontech.com/bug-view-264587.html
=> fix: 修改标题账户设置

src/app/dman.cpp, src/base/utils.cpp, src/base/utils.h
manual treeland adaptation
Log: manual treeland adaptation
=> fix: manual treeland adaptation

debian/deepin-manual.postinst, misc/deepin-manual.service
Fix the issue of manual. open dbus service response timeout
Log: Fix the issue of manual. open dbus service response timeout
Bug: https://pms.uniontech.com/bug-view-269561.html
=> fix: Fix the issue of manual. open dbus service response timeout

src/app/dman.cpp, src/base/command.cpp, src/base/command.h, src/controller/shellobj.cpp, src/controller/shellobj.h, src/dbus/dmanwatcher.cpp, src/dbus/dmanwatcher.h
Remove command line calls through shell parsing
Log: Remove command line calls through shell parsing
Task: https://pms.uniontech.com/task-view-355359.html
=> fix: [cmd] Remove command line calls through shell parsing

src/app/dman.cpp
修复在帮助手册打开后，再次打开帮助手册崩溃
Bug: https://pms.uniontech.com/bug-view-271185.html 
https://pms.uniontech.com/bug-view-268377.html
Log: 修复在帮助手册打开后，再次打开帮助手册崩溃
=> fix: 修复在帮助手册打开后，再次打开帮助手册崩溃

arm64/linglong.yaml, debian/changelog, linglong.yaml, src/app/dman.cpp
With the value of XDG_DATA_DIRS before the fix, we can only view the help information of deepin-manual itself. In order to view the help manuals in the host application and linglong application, let's add the relevant paths.
Log: Adapt linglong
=> fix: fail to view application manual

arm64/linglong.yaml, debian/changelog, linglong.yaml, src/dbus/CMakeLists.txt, src/dbus/com.deepin.Manual.Search.service.in
Because the DBUS .Service file uses a fixed executable file path, it has caused the failure to start the app in the linglong environment. Let us dynamically generate this file.
Log: fix fail to launch linglong app via dbus
Bug: https://pms.uniontech.com/bug-view-282545.html
Bug: https://pms.uniontech.com/bug-view-282353.html
Bug: https://pms.uniontech.com/bug-view-281637.html
Bug: https://pms.uniontech.com/bug-view-282113.html
=> fix: fix fail to launch linglong app via dbus

arm64/linglong.yaml, debian/changelog, linglong.yaml
Update changelog
Log: Update changelog
=> Chore: Update changelog

arm64/linglong.yaml, debian/changelog, linglong.yaml
Bump version to 6.5.9
Log: Bump version to 6.5.9
=> chore: Bump version to 6.5.9

src/app/dman_helper.cpp
dmanHelper uses the directories in XDG_DATA_DIRS to create a search database. Before the fix, dmanHelper found very few application help. In order to search for help information for host applications and linglong applications, let's add the relevant paths.
Log: Adapt linglong
Bug: https://pms.uniontech.com/bug-view-290335.html
=> fix: fix the issue of incomplete search results

arm64/linglong.yaml, debian/changelog, debian/control, linglong.yaml, loong64/linglong.yaml
Updated the version of deepin-manual to 6.5.18 in all relevant files. Added a new dependency for libqt6webenginecore6-bin in the control file. Updated the changelog to reflect the new version.
=> chore: Bump version to 6.5.18 and update dependencies

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, src/base/utils.cpp
fix: Refactor uosEditionType checks in getSystemManualList function
- Replaced multiple calls to Utils::uosEditionType() with a single call to improve performance and readability.
- Added a condition to prevent adding certain applications to the list for UOS Community edition.
- Enhanced debug output for better tracking of application list generation.
bug: https://pms.uniontech.com/bug-view-310445.html
=> fix: Refactor uosEditionType checks in getSystemManualList function

debian/changelog
- Bump version to 6.5.23.
- Reflect changes in debian/changelog for release preparation.
log: Update version to 6.5.23
=> chore: Update version to 6.5.23

src/view/manual_proxy.cpp, src/view/web_window.cpp, src/view/web_window.h
The frontend requires image paths for display. However, some icon paths cannot be found in the current theme's directory, necessitating an expanded search path, which slows down performance.
This change addresses the issue by converting icons to base64 for display.
Bug: https://pms.uniontech.com/bug-view-317869.html
=> Fix: Page lags when scrolling in Help Manual

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
chore: Update package URLs and digests in linglong.yaml files
- Updated coreutils and cryfs package URLs and digests across all architectures.
log: Update package URLs and digests in linglong.yaml files
=> chore: Update package URLs and digests in linglong.yaml files

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, src/base/utils.cpp, src/base/utils.h, src/view/manual_proxy.cpp
chore: Update package URLs in linglong.yaml files for crimson_25.0
- Updated package source URLs across all architectures from testing25_daily to crimson_25.0.
- Ensured consistency in package paths and digests for improved package management.
This change aligns the package sources with the new release version.
This change aligns the package sources with the new release version.
fix: Add compatibility function for system omit prefixes
- Introduced `systemToOmitCompat` to handle prefix selection based on UosEdition type.
- Updated `appToPath` to utilize the new compatibility function for improved handling of application paths.
This change enhances the flexibility of prefix management across different Uos editions.
bug: https://pms.uniontech.com/bug-view-324463.html
=>     fix: Add compatibility function for system omit prefixes &     chore: Update package URLs in linglong.yaml files for crimson_25.0

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, src/base/command.cpp
- Updated SpawnCmd to wait for process completion with a default timeout. This change improves the robustness of command execution by preventing indefinite hangs.
Log: Fix the database may be incompletely created, resulting in no searches.
=> fix: Implement process timeout handling in SpawnCmd
