.github/workflows/backup-to-gitlab.yml
移除 gitee 仓库镜像 CI
相关：https://github.com/linuxdeepin/.github/pull/200
=> chore: remove one of the failed mirrors

CMakeLists.txt, src/controller/search_db.cpp, src/web_dist/toManual/index.js
Description: js会自动将转码后的%25转码回% 导致字符识别出错
Log:搜索框中输入多个特殊字符，且包含“%”，按enter键，界面显示空白，返回按钮缺失.
Bug:https://pms.uniontech.com/bug-view-101788.html
=> fix: 搜索框中输入多个特殊字符，且包含“%”，按enter键，界面显示空白，返回按钮缺失.

CMakeLists.txt
Description: 仅在debug下开启UT测试
Log: 仅在debug下开启UT测试
=> fix: 仅在debug下开启UT测试

src/web_dist/toManual/index.js
Description: 搜索下拉框，没有进行base64编码，进行转码的时候，会出错
Log: 输入字母搜索，选择提示项进行跳转，显示空白
Bug:https://pms.uniontech.com/bug-view-149669.html
=> fix: 输入字母搜索，选择提示项进行跳转，显示空白

src/CMakeLists.txt, src/app/dman.cpp, src/base/eventlogutils.cpp, src/base/eventlogutils.h
Description: 提交埋点需求，采集帮助手册启动数据
Log: 提交埋点需求，采集帮助手册启动数据
=> feat: 提交埋点需求，采集帮助手册启动数据

src/controller/filewatcher.h
Description: 帮助手册需要适配解析edu类型md文件
Log: 帮助手册需要适配解析edu类型md文件
Bug: https://pms.uniontech.com/bug-view-155913.html
=> fix: 帮助手册需要适配解析edu类型md文件

debian/deepin-manual.1, debian/dmanHelper.1
Description: 开源合规debian目录.1文件整改
Log: 开源合规debian目录.1文件整改
=> fix: 开源合规debian目录.1文件整改

src/controller/search_db.cpp, src/controller/search_db.h, src/controller/search_manager.cpp, src/controller/search_manager.h, src/controller/window_manager.cpp, src/controller/window_manager.h, src/dbus/manual_search_proxy.cpp, src/view/web_window.cpp, src/view/web_window.h
Description: 补充提交文件
Log: 补充提交文件
Bug: https://pms.uniontech.com/bug-view-160195.html
=> fix: 补充提交文件 

src/base/eventlogutils.h, src/controller/argument_parser.cpp
Description: 帮助手册数据埋点需求-统计应用打开帮助手册
Log: 帮助手册数据埋点需求-统计应用打开帮助手册
=> feat: 帮助手册数据埋点需求-统计应用打开帮助手册

src/CMakeLists.txt, src/app/dman.cpp, src/base/utils.cpp, src/controller/search_manager.h, src/controller/window_manager.cpp, tests/src/base/ut_utils.cpp, tests/src/controller/ut_filewatcher.cpp, tests/src/view/ut_manual_proxy.cpp
fix some compile problems
Log: fix some compile problems
Change-Id: I937998395e9d0171d45dc50e5ed883ee1763d636
=> chore: fix some compile problems

src/CMakeLists.txt, src/view/web_window.cpp, src/web_dist/toManual/index.js, tests/CMakeLists.txt
fix tests compile problems
Log: fix tests compile problems
=> chore: fix tests compile problems

src/app/dman.cpp, src/base/utils.cpp, src/controller/argument_parser.cpp, src/dbus/dbus_consts.cpp, src/dbus/dbus_consts.h, src/dbus/launcher_interface.h
reserve V20 dde dbus interfaces, add V23 dde dbus interfaces
Log: adapt V23 DDE DBus interfaces
=> feat: adapt V23 DDE DBus interfaces

patches/fix-linglong.patch
根据最新代码重新生成玲珑打包patch文件内容
Log: 修复玲珑打包加载patch失败的问题
=> fix: 修复玲珑打包加载patch失败的问题

patches/fix-linglong.patch
=> fix: patch文件更新

debian/changelog
Update version to 6.0.1
Log: Update version to 6.0.1
=> Chore: Update version to 6.0.1

debian/changelog
update version 6.0.2
Log: update version 6.0.2
=> chore: update version 6.0.2

patches/fix-linglong.patch
use patch config linglong build
Log: add linglong build patch
=> chore: add linglong build patch

debian/changelog
修复某些应用图标显示为撕裂图的问题
Log: Update Version 6.0.3
=> chore: Update Version 6.0.3

debian/changelog
Update version to 6.0.6(community)
Log: Update version to 6.0.6(community)
=> chore: Update version to 6.0.6(community)

src/view/theme_proxy.cpp
=> fix: build failure on dtkgui 5.6.12

src/app/generate_search_db.cpp, src/base/command.cpp, src/view/image_viewer_proxy.cpp, src/view/search_proxy.cpp
=> feat: support dtk 5.6.17

src/controller/helpermanager.cpp, src/controller/search_db.cpp, src/web/toManual/js/index.jsx, src/web/toManual/package-lock.json, src/web/toManual/package.json, src/web/toManual/sass/app.scss, src/web/toManual/sass/index.scss, src/web/toManual/sass/search.scss, src/web_dist/toManual/index.css, src/web_dist/toManual/index.js
修复切换到繁体后搜索不到视频
修复搜索关键字为数字或英文，搜索结果中的视频链接无法打开
修复维语“视频指南”分组右侧的“查看全部”显示为两排
快速入门banner中的文字修改为固定大小，不随系统字体缩放
调整服务与支持图标位置
Log: Quick Start and Video Guide modules problem repair
Bug: https://pms.uniontech.com/bug-view-241059.html
https://pms.uniontech.com/bug-view-241195.html
https://pms.uniontech.com/bug-view-241175.html
https://pms.uniontech.com/bug-view-241083.html
https://pms.uniontech.com/bug-view-241181.html
=> fix: Quick Start and Video Guide modules problem repair

debian/changelog
=> chore: tag 6.0.8

src/controller/search_db.cpp, src/web/toManual/js/App.js, src/web/toManual/sass/search.scss, src/web_dist/toManual/index.css, src/web_dist/toManual/index.js
搜索结果图片显示问题修复
调整字体颜色
Log: 搜索结果图片显示问题修复
=> fix: 搜索结果图片显示问题修复

debian/changelog
=> chore: tag 6.0.9

debian/changelog
=> chore: tag 6.0.10

debian/changelog
=> chore: tag 6.0.11

src/view/web_window.cpp
修复服务与支持进程未退出时再次打开失败
Log: 修复服务与支持进程未退出时再次打开失败
Bug: https://pms.uniontech.com/bug-view-242111.html
=> fix: 服务与支持进程未退出时再次打开失败

debian/changelog
=> chore: tag 6.0.12

src/web/toManual/js/App.js, src/web/toManual/sass/app.scss, src/web/toManual/sass/index.scss, src/web_dist/toManual/index.css, src/web_dist/toManual/index.js
主页面字体调整、tooltip样式修改
Log: 主页面字体调整、tooltip样式修改
Bug: https://pms.uniontech.com/bug-view-241593.html
https://pms.uniontech.com/bug-view-241597.html
https://pms.uniontech.com/bug-view-243239.html
=> fix: 主页面字体调整、tooltip样式修改

debian/changelog
Update version to 6.0.13
相关PR:
* #466
* #468
* #469
* #470
Log: Update version 6.0.13
=> chore: Update version to 6.0.13

src/view/web_window.cpp
Fix potential crash issues
Log: Fix potential crash issues
=> fix: Fix potential crash issues

.reuse/dep5, CMakeLists.txt, debian/control, misc/deepin-manual.service, src/dbus/com.deepin.Manual.Open.service
Issue: https://github.com/linuxdeepin/developer-center/issues/8964
=> chore: use systemd service to start dman

debian/control
fix systemd package compile problem
Log: fix systemd package compile problem
=> fix: fix systemd package compile problem

src/CMakeLists.txt
adapt V25 linglong.yaml
Log: adapt V25 linglong.yaml
=> feat: adapt V25 linglong.yaml

src/base/utils.cpp
manual treeland adaptation
Log: manual treeland adaptation
=> fix: manual treeland adaptation

arm64/linglong.yaml, linglong.yaml
Optimize the dependencies and fix build error issue on arm64.
Log: Fix linglong arm64 build.
=> fix: [linglong]Fix arm64 build

src/view/web_window.cpp, src/view/web_window.h
adapt compact mode
Log: adapt compact mode
Bug: https://pms.uniontech.com/bug-view-279717.html
=> fix: adapt compact mode

debian/changelog
update version to 6.5.6
Log: udpate version to 6.5.6
=> chore: udpate version to 6.5.6

arm64/linglong.yaml, linglong.yaml
update linglong version to 6.5.6
Log: update linglong version to 6.5.6
=> chore: update linglong version to 6.5.6

src/view/web_window.cpp
The issue of shutdown and restart is fixed
Log: The issue of shutdown and restart is fixed
=> fix: The issue of shutdown and restart is fixed

deploy_dep, loong64/linglong.yaml
Adapt linglong for loong64.
Log: Adapt linglong for loong64.
Task: https://pms.uniontech.com/task-view-368689.html
=> chore: Adapt linglong for loong64

arm64/linglong.yaml, linglong.yaml, loong64/linglong.yaml
Update linglong version.
Log: Update linglong version
=> chore: update linglong version

src/controller/helpermanager.cpp, src/controller/helpermanager.h
修复关闭程序产生coredump问题
Log: 修复关闭程序产生coredump问题
Bug: https://pms.uniontech.com/bug-view-291437.html
=> fix: 修复关闭程序产生coredump问题

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.10
Log: Bump version to 6.5.10
=> chore: Bump version to 6.5.10

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.12
Log: Bump version to 6.5.12
=> chore: Bump version to 6.5.12

src/configs/dbus/FilesUpdateAdaptor.cpp, src/configs/dbus/FilesUpdateAdaptor.h, src/configs/dbus/Launcher1Adaptor.cpp, src/configs/dbus/Launcher1Adaptor.h, src/configs/dbus/LauncherAdaptor.cpp, src/configs/dbus/LauncherAdaptor.h, src/configs/dbus/OpenAdaptor.cpp, src/configs/dbus/OpenAdaptor.h, src/configs/dbus/SearchAdaptor.cpp, src/configs/dbus/SearchAdaptor.h
add dbus adaptor classes for launcher and manual service interfaces
Log: add dbus adaptor classes for launcher and manual service interfaces
=> chore: add dbus adaptor classes for launcher and manual service interfaces

src/base/utils.cpp
适配个人版
Task: https://pms.uniontech.com/task-view-80519.html
Log: 适配个人版
=> fix: 适配个人版

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.16
Log: Bump version to 6.5.16
=> chore: Bump version to 6.5.16

.reuse/dep5, manual-assets/org.deepin.manual.customui.json, src/CMakeLists.txt, src/base/utils.cpp
可配置显示服务与支持
Task: https://pms.uniontech.com/task-view-374189.html
Log: 可配置显示服务与支持
=> fix: 可配置显示服务与支持

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.20
Log: Bump version to 6.5.20
=> chore: Bump version to 6.5.20

src/base/utils.cpp, src/base/utils.h, src/controller/helpermanager.cpp, src/view/manual_proxy.cpp
- Using a new method to obtain version information to prevent incorrect retrieval under the Linglong environment.
bug: https://pms.uniontech.com/bug-view-281679.html
=> fix: Add uosEditionType function to retrieve UOS edition

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
- Bump version to 6.5.24
log: Bump version to 6.5.24
=> chore: Update version to 6.5.24

src/CMakeLists.txt, src/app/dman.cpp, src/base/command.cpp, src/base/ddlog.h, src/base/logger.cpp, src/base/logger.h, src/base/utils.cpp, src/controller/argument_parser.cpp, src/controller/config_manager.cpp, src/controller/filewatcher.cpp, src/controller/helpermanager.cpp, src/controller/search_db.cpp, src/controller/shellobj.cpp, src/controller/window_manager.cpp, src/dbus/manual_filesupdate_proxy.cpp, src/dbus/manual_open_proxy.cpp, src/dbus/manual_search_proxy.cpp, src/view/image_viewer_proxy.cpp, src/view/jscontext.cpp, src/view/manual_proxy.cpp, src/view/search_proxy.cpp, src/view/web_window.cpp, src/view/widget/image_viewer.cpp, src/view/widget/search_edit.cpp, tests/CMakeLists.txt
Format the log output.
Log: Format the log output.
=> chore: [log] Format log output.

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
- Bump version to 6.5.27 in all relevant configuration files.
=> chore: Update version to 6.5.27

src/app/dman_helper.cpp, src/base/logger.cpp, src/base/utils.cpp, src/configs/dbus/FilesUpdateAdaptor.cpp, src/configs/dbus/Launcher1Adaptor.cpp, src/configs/dbus/LauncherAdaptor.cpp, src/configs/dbus/OpenAdaptor.cpp, src/configs/dbus/SearchAdaptor.cpp, src/controller/argument_parser.cpp, src/controller/config_manager.cpp, src/controller/filewatcher.cpp, src/controller/helpermanager.cpp, src/controller/search_db.cpp, src/controller/search_manager.cpp, src/controller/window_manager.cpp, src/dbus/dmanwatcher.cpp, src/dbus/manual_filesupdate_proxy.cpp, src/dbus/manual_open_proxy.cpp, src/dbus/manual_search_adapter.cpp, src/dbus/manual_search_proxy.cpp, src/view/manual_proxy.cpp, src/view/theme_proxy.cpp, src/view/web_window.cpp, src/view/widget/image_viewer.cpp, src/view/widget/search_button.cpp, src/view/widget/search_completion_delegate.cpp, src/view/widget/search_completion_listview.cpp, src/view/widget/search_completion_window.cpp
Add more logs: 86.52%
Log: more logs.
=> chore: [log] more logs.

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml, src/resources/deepin-manual.desktop
- update version to 6.5.38
log: update version to 6.5.38
=> chore: Update version to 6.5.38
